-- =======================================================
-- RESTAURANT MANAGEMENT SYSTEM - RELATIONAL SCHEMA (DDL)
-- =======================================================

-- 1. Restaurant Branch Table
CREATE TABLE "Resturant_Branch" (	
    "B_NUMBER" NUMBER,
    "City" NVARCHAR2(20),
    "Street" NVARCHAR2(20),
    "ZIP_Code" NVARCHAR2(20),
    "Email" NVARCHAR2(20),
    "Phone" NVARCHAR2(15),
    CONSTRAINT "BRANCH_PK" PRIMARY KEY ("B_NUMBER") USING INDEX ENABLE
);

-- 2. Dish Table
CREATE TABLE "DISH" (	
    "NAME" NVARCHAR2(30),
    "Price" NUMBER,
    "Recipe" NVARCHAR2(50),
    "Food_Allergy" NVARCHAR2(50),
    "Serving_Time" NVARCHAR2(50),
    CONSTRAINT "DISH_PK" PRIMARY KEY ("NAME") USING INDEX ENABLE
);

-- 3. Person Table
CREATE TABLE "PERSON" (
    "ID" NUMBER,
    "First_Name" NVARCHAR2(15),
    "Middle_Name" NVARCHAR2(15),
    "Last_Name" NVARCHAR2(15),
    "Phone" NVARCHAR2(20),
    "Email" NVARCHAR2(20),
    "Address" NVARCHAR2(30),
    CONSTRAINT "PERSON_PK" PRIMARY KEY ("ID") USING INDEX ENABLE
);

-- 4. Person Order Table
CREATE TABLE "PERSON_ORDER" (
    "NUM" NUMBER,
    "O_Time" NVARCHAR2(15),
    "O_Date" NVARCHAR2(15),
    "Comments" NVARCHAR2(50),
    "Person_ID" NUMBER,
    CONSTRAINT "PERSON_ORDER_PK" PRIMARY KEY ("NUM") USING INDEX ENABLE
);
ALTER TABLE "PERSON_ORDER" ADD CONSTRAINT "PERSON_ORDER_FK" FOREIGN KEY ("Person_ID") REFERENCES "PERSON" ("ID") ON DELETE CASCADE ENABLE;

-- 5. Chef Table
CREATE TABLE "CHEF" (	
    "PERSONID" NUMBER,
    "SALARY" NUMBER,
    "Speciality" NVARCHAR2(30),
    "Branchnumber" NUMBER,
    "Chef_TutorID" NUMBER,
    CONSTRAINT "CHEF_PK" PRIMARY KEY ("PERSONID") USING INDEX ENABLE
);
ALTER TABLE "CHEF" ADD CONSTRAINT "CHEF_FK" FOREIGN KEY ("PERSONID") REFERENCES "PERSON" ("ID") ON DELETE CASCADE ENABLE;
ALTER TABLE "CHEF" ADD CONSTRAINT "CHEF_FK2" FOREIGN KEY ("Branchnumber") REFERENCES "Resturant_Branch" ("B_NUMBER") ON DELETE CASCADE ENABLE;
ALTER TABLE "CHEF" ADD CONSTRAINT "CHEF_FK3" FOREIGN KEY ("Chef_TutorID") REFERENCES "CHEF" ("PERSONID") ON DELETE CASCADE ENABLE;

-- 6. Employee Table
CREATE TABLE "EMPLOYEE" (	
    "PERSONID" NUMBER,
    "Position" NVARCHAR2(15),
    "Salary" NUMBER,
    CONSTRAINT "EMPLOYEE_3_PK" PRIMARY KEY ("PERSONID") USING INDEX ENABLE
);
ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_3_FK" FOREIGN KEY ("PERSONID") REFERENCES "PERSON" ("ID") ON DELETE CASCADE ENABLE;

-- 7. Customer Table
CREATE TABLE "CUSTOMER" (	
    "PERSONID" NUMBER,
    "PASSWORD" NVARCHAR2(15),
    CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("PERSONID") USING INDEX ENABLE
);
ALTER TABLE "CUSTOMER" ADD CONSTRAINT "CUSTOMER_FK" FOREIGN KEY ("PERSONID") REFERENCES "PERSON" ("ID") ON DELETE CASCADE ENABLE;

-- 8. Provide Table
CREATE TABLE "PROVIDE" (	
    "BRANCHNUM" NUMBER,
    "DishNAME" NVARCHAR2(30),
    CONSTRAINT "PROVIDE_PK" PRIMARY KEY ("BRANCHNUM", "DishNAME") USING INDEX ENABLE
);
ALTER TABLE "PROVIDE" ADD CONSTRAINT "PROVIDE_FK" FOREIGN KEY ("BRANCHNUM") REFERENCES "Resturant_Branch" ("B_NUMBER") ON DELETE CASCADE ENABLE;
ALTER TABLE "PROVIDE" ADD CONSTRAINT "PROVIDE_FK2" FOREIGN KEY ("DishNAME") REFERENCES "DISH" ("NAME") ON DELETE CASCADE ENABLE;

-- 9. Cooking Table
CREATE TABLE "COOKING" (	
    "ChefID" NUMBER,
    "DishNAME" NVARCHAR2(30),
    CONSTRAINT "COOKING_PK" PRIMARY KEY ("ChefID", "DishNAME") USING INDEX ENABLE
);
ALTER TABLE "COOKING" ADD CONSTRAINT "COOKING_FK" FOREIGN KEY ("ChefID") REFERENCES "CHEF" ("PERSONID") ON DELETE CASCADE ENABLE;
ALTER TABLE "COOKING" ADD CONSTRAINT "COOKING_FK2" FOREIGN KEY ("DishNAME") REFERENCES "DISH" ("NAME") ON DELETE CASCADE ENABLE;

-- 10. HasOrderCook Table
CREATE TABLE "HASORDERCOOK" (	
    "ORDERNUM" NUMBER,
    "DishNAME" NVARCHAR2(30),
    CONSTRAINT "HASORDERCOOK_PK" PRIMARY KEY ("ORDERNUM", "DishNAME") USING INDEX ENABLE
);
ALTER TABLE "HASORDERCOOK" ADD CONSTRAINT "HASORDERCOOK_FK" FOREIGN KEY ("ORDERNUM") REFERENCES "PERSON_ORDER" ("NUM") ON DELETE CASCADE ENABLE;
ALTER TABLE "HASORDERCOOK" ADD CONSTRAINT "HASORDERCOOK_FK2" FOREIGN KEY ("DishNAME") REFERENCES "DISH" ("NAME") ON DELETE CASCADE ENABLE;


-- =======================================================
-- DATA MANIPULATION & COMPLEX QUERIES (DML)
-- =======================================================

-- Query 1: Filter person by ID
select * from Person where ID = 1;

-- Query 2: Aggregate count of chefs grouped by salary with minimum threshold
select count(personid) , salary from chef group by salary having salary>=9000;

-- Query 3: Nested subquery retrieving person records associated with Chefs
select ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, ADDRESS, PHONE, EMAIL 
from PERSON where id in(select PERSONID from CHEF);

-- Query 4: Multi-level subquery filtering dishes cooked by highly paid chefs
select NAME, PRICE, RECIPE, FOOD_ALLERGY, SERVING_TIME 
from DISH 
where name in(select DISHNAME from COOKING where CHEFID=(select PERSONID from CHEF where salary>7000));

-- Query 5: INNER JOIN across Person and Chef entities
select ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, ADDRESS, PHONE, EMAIL 
from PERSON inner join chef on id=personid;

-- Query 6: Multi-table LEFT OUTER JOIN across Dish, Cooking, and Chef relations
select NAME , Price , Recipe , Food_Allergy , Serving_Time 
from DISH left outer join COOKING on NAME = DishNAME left outer join CHEF on ChefID = PERSONID;
